export enum EventType {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_UPDATED = 'ORDER_UPDATED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SHIPPING_CREATED = 'SHIPPING_CREATED',
  SHIPPING_DELIVERED = 'SHIPPING_DELIVERED',
  REVIEW_REQUESTED = 'REVIEW_REQUESTED',
}
